"""Updates columns for pictures

Revision ID: 368590b832aa
Revises: db5212ac1720
Create Date: 2024-01-19 19:55:36.228662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368590b832aa'
down_revision = 'db5212ac1720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_pic', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.BLOB(), nullable=True))
        batch_op.drop_column('book_pic')

    # ### end Alembic commands ###
