"""Updates section with dates

Revision ID: 7c6c580e18d4
Revises: 368590b832aa
Create Date: 2024-01-21 11:09:17.793229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6c580e18d4'
down_revision = '368590b832aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.alter_column('visits',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=60), nullable=False))
        batch_op.alter_column('visits',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)

    # ### end Alembic commands ###
