"""idk

Revision ID: e4d23a568b73
Revises: 41e3347de849
Create Date: 2024-01-26 19:21:16.373364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d23a568b73'
down_revision = '41e3347de849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_analytics')
    op.drop_table('user_analytics')
    op.drop_table('section_analytics')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visits', sa.Integer(), nullable=True))

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['book_id'])
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requests', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('no_books_requested', sa.Integer(), nullable=True))

    with op.batch_alter_table('users_books', schema=None) as batch_op:
        batch_op.alter_column('doi',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('doi',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('no_books_requested')
        batch_op.drop_column('logins')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('requests')
        batch_op.drop_column('visits')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('visits')
        batch_op.drop_column('requests')

    op.create_table('section_analytics',
    sa.Column('section_id', sa.INTEGER(), nullable=False),
    sa.Column('visits', sa.INTEGER(), nullable=True),
    sa.Column('requests', sa.INTEGER(), nullable=True),
    sa.Column('most_frequent_user', sa.INTEGER(), nullable=True),
    sa.Column('most_popular_book', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['most_frequent_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['most_popular_book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('user_analytics',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('favourite_book', sa.INTEGER(), nullable=True),
    sa.Column('logins', sa.INTEGER(), nullable=True),
    sa.Column('no_books_requested', sa.INTEGER(), nullable=True),
    sa.Column('favourite_section', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['favourite_book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['favourite_section'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('book_analytics',
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('visits', sa.INTEGER(), nullable=True),
    sa.Column('requests', sa.INTEGER(), nullable=True),
    sa.Column('longest_user', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['longest_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    # ### end Alembic commands ###
